### ISSUE TITLE
Prepare the project for release-build

### ISSUE THREAD

**Issue by Chringo** [Chringo/SSP#113]
There are probably several unknown problems that prevent us from running it in release-build. The more we stall this issue the harder it will get to solve it. 
If you encounter a problem or solved something that helps us build in release, please log it in this issue so that we can perhaps run it in release eventually.

**Comment by Chringo** [comment]
Since the compiler helps us align data in debug it's not a problem there but this warning is popping up in several places:
Compiler warning - C4316: https://msdn.microsoft.com/en-us/library/dn448573.aspx
Someone on SO with a similar problem: http://stackoverflow.com/questions/20104815/warning-c4316-object-allocated-on-the-heap-may-not-be-aligned-16#20104987

**Comment by Chringo** [comment]
#114 resolves a few errors where preprocessor definitions are not handled safely.

**Comment by TobbetheStalker** [comment]
#138 resolves this entire issue.
