### ISSUE TITLE
Gravity is too low

### ISSUE THREAD

**Issue by Marcets423** [Chringo/SSP#262]
I noticed when the character is supposed to fall down he falls too slow. This allows for the character to run in the air, which allows him to run over gaps, such as the gap at the end of the intro level. The forward velocity is greater than the velocity down i think.

**Comment by Chringo** [comment]
Still not resolved. Now that we have maps that can be tested we should definitely test and adjust gameplay mechanics.
This issue must be closed in the next sprint.
