### ISSUE TITLE
Look for a way to minimize C4251-warnings

### ISSUE THREAD

**Issue by Chringo** [Chringo/SSP#29]
They are currently two-thirds of our warnings.
References: 
https://msdn.microsoft.com/query/dev14.query?appId=Dev14IDEF1&l=EN-US&k=k(C4251)
https://www.codeproject.com/articles/28969/howto-export-c-classes-from-a-dll

**Comment by Pistonnoob** [comment]
I have changed the projects in branch Camera to suppress all C4251 warnings.

**Comment by Chringo** [comment]
C4251 warnings temporarily suppressed with pull request #43

**Comment by Chringo** [comment]
With the tests made in pull request #90 we can now finally reduce the number of warnings that we currently have of C4251. #90 removed C4251 warnings in NetworkDLL.

**Comment by Chringo** [comment]
#91 removed C4251 warnings in ResourceLib

**Comment by Chringo** [comment]
#104 removed C4251 warnings in GraphicsDLL

**Comment by Chringo** [comment]
#117 removed C4251 warnings in PhysicsDLL. We've eliminated all warnings!
