### ISSUE TITLE
How shall the resource handler be used in the engine?

### ISSUE THREAD

**Issue by Marcets423** [Chringo/SSP#30]
Currently the graphics handler uses the resource handler to get data for rendering.

But there has been talk about using the resource handler in other places of the engine. For example, the animation handler will need animation data quite frequently. And the game(engine) should trigger the "load level" events when moving to a new level.

Currently the resource handler is a singleton. but we might face big issues going forward if we access the data on multiple threads.

**Comment by pixet93** [comment]
I strongly suggest that several people are needed to handle the way the animations are to be structured in the engine, because currently the data is ready to be used but nothing in the system is ready for animations. 
See #39
