### ISSUE TITLE
How do we integrate animations in the system?

### ISSUE THREAD

**Issue by pixet93** [Chringo/SSP#39]
The dependencies that are to be required for the animations is the ResourceLib (to gain access of the skeleton and animation data). The overall structure of handling animations in the engine is currently none. Several people are required to solve this matter,

**Comment by pixet93** [comment]
As of today, the idea to integrate the animations into the game system, is by having this tested for the player first. What needs to be solved is how to handle the animation components of one but also later for several animatible game objects.

**Comment by Chringo** [comment]
Solved with pull request #217
