### ISSUE TITLE
Physics is frame dependent

### ISSUE THREAD

**Issue by Pistonnoob** [Chringo/SSP#65]
The physics is frame dependent.

**Comment by TobbetheStalker** [comment]
The fix exist in the Demo branch but since the camera is incomplete, I dont want to merge it with dev. We will probably have to redo the fix sepratly.

**Comment by Chringo** [comment]
Is this solved with following commit?
https://github.com/Chringo/SSP/pull/74/commits/b52387f29a73a36184fcb4799ff83b9c79afca4a

This commit has been merged with dev from pull request #74.

**Comment by Chringo** [comment]
Confirmed.
